{% set name = "nomad-parser-plugins-atomistic" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_parser_plugins_atomistic-{{ version }}.tar.gz
  sha256: cedec9912f7068bc9f6b4aa5ca6de48dcd3495c9d04f677043eba021ac94de91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - nomad-lab >=1.3.13
    - nomad-schema-plugin-simulation-workflow >=1.0.1
    - nomad-schema-plugin-run >=1.0.1
    - nomad-parser-plugins-simulation >=1.0.2
    - lxml >=5.2
    - mdanalysis >=2.8.0,<3.0.0
    - panedr >=0.2
    - scipy >=1.7.1
    - pydantic >=1.10.8
    - ase >=3.22.0
    - numpy >=1.22.4
    - h5py >=3.6.0

test:
  imports:
    - atomisticparsers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nomad-coe/atomistic-parsers
  summary: Collection of NOMAD parsers for atomistic codes.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
