schema_version: 1

context:
  name: nomad-parser-plugins-atomistic
  version: "1.0.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/nomad_parser_plugins_atomistic-${{ version }}.tar.gz
  sha256: 3ead5953c766de262b9d1958765a112d2b23eb74e03e7cc5f791adb5f1ff5685

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0.0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - nomad-lab >=1.3.13
    - nomad-schema-plugin-simulation-workflow >=1.0.1
    - nomad-schema-plugin-run >=1.0.1
    - nomad-parser-plugins-simulation >=1.0.2
    - lxml >=5.2
    - mdanalysis >=2.8.0,<3.0.0
    - panedr >=0.2
    - scipy >=1.7.1
    - pydantic >=1.10.8
    - ase >=3.22.0
    - numpy >=1.22.4
    - h5py >=3.6.0

tests:
  - python:
      imports:
        - atomisticparsers
      pip_check: false
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Collection of NOMAD parsers for atomistic codes.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/nomad-coe/atomistic-parsers

extra:
  recipe-maintainers:
    - jan-janssen
